name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: latest
    - run: corepack enable
    - run: pnpm i
    - run: pnpm build
