name: Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 16.x

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: latest
  
    - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 16.x
  
    - run: pnpm i && pnpm build
